# El nombre que identifica a este microservicio en el sistema
spring.application.name=catalogo

# CONFIGURACIÓN DE LA BASE DE DATOS

# La dirección (URL) donde vive mi base de datos en Laragon
# jdbc:mysql://localhost:3306/ es el servidor, y db_catalogo_pc es mi base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_catalogo_pc

# El nombre de usuario para entrar a MySQL (en Laragon suele ser root)
spring.datasource.username=root

# La contraseña para entrar (en Laragon viene vacía por defecto)
spring.datasource.password=

# El traductor (Driver) que permite que Java hable con MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE HIBERNATE (JPA)

# validate le dice a Java Solo revisa que las tablas existan en la DB
# Esto es porque quiero que Flyway se encargue de crear las tablas.
spring.jpa.hibernate.ddl-auto=validate

# true hace que Java me muestre en la consola todas las consultas SQL que haga
# Es muy útil para nosotros ver qué está pasando detrás
spring.jpa.show-sql=true

# CONFIGURACIÓN DE FLYWAY 

# true activa Flyway para que lea nuestros archivos de la carpeta migration
# y cree las tablas automáticamente al iniciar la aplicación
spring.flyway.enabled=true
