# Nombre del microservicio para identificarlo en el ecosistema 
spring.application.name=pcfactory

# URL de conexión protocolo (jdbc), motor (mysql), servidor (localhost), puerto (3306) y nombre de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_pcfactory

# Credenciales de acceso a MySQL
spring.datasource.username=root
spring.datasource.password=

# Configuración de JPA y Hibernate

# update permite que Hibernate cree las tablas faltantes o agregue columnas nuevas sin borrar tus datos
spring.jpa.hibernate.ddl-auto=update 

# Muestra en la consola de Spring todas las consultas SQL que se ejecutan automáticamente
spring.jpa.show-sql=true 

# Hace que el SQL en consola sea fácil de leer con saltos de línea y espacios en lugar de una sola línea larga
spring.jpa.properties.hibernate.format_sql=true 

# Indica el dialecto específico de MySQL para que Hibernate sepa qué sintaxis exacta usar
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect